---
# Backup Tasks - Separate from discovery for better organization

- name: Backup - Create backup directory
  ansible.builtin.file:
    path: "{{ jenkins_migration_docker_dir }}/backup"
    state: directory
    mode: "0755"

- name: Backup - Find backup files older than 7 days
  ansible.builtin.find:
    paths: "{{ jenkins_migration_docker_dir }}/backup"
    patterns: "*.backup"
    age: "7d"
    age_stamp: mtime
  register: old_backup_files
  changed_when: false

- name: Backup - Remove backups older than 7 days
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ old_backup_files.files }}"
  loop_control:
    label: "{{ item.path | basename }}"

- name: Backup - Find all remaining backup files
  ansible.builtin.find:
    paths: "{{ jenkins_migration_docker_dir }}/backup"
    patterns: "*.backup"
  register: all_backup_files
  changed_when: false

- name: Backup - Remove oldest backups (keep last 5)
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ (all_backup_files.files | sort(attribute='mtime'))[:-5] }}"
  loop_control:
    label: "{{ item.path | basename }}"

- name: Backup - Create systemd service backup
  ansible.builtin.copy:
    src: "{{ jenkins_migration_constants.systemd_service_path }}"
    dest: "{{ jenkins_migration_docker_dir }}/backup/jenkins.service.backup"
    remote_src: true
    mode: "0644"
  register: systemd_backup_result
  failed_when: false

- name: Backup - Warn if systemd service backup failed
  ansible.builtin.debug:
    msg: >-
      ⚠️  WARNING: Could not backup systemd service file -
      {{ systemd_backup_result.msg | default('Unknown error') }}
  when: systemd_backup_result is failed

- name: Backup - Create Jenkins config.xml backup
  ansible.builtin.copy:
    src: "{{ jenkins_migration_discovered_home }}/{{ jenkins_migration_constants.jenkins_config_file }}"
    dest: "{{ jenkins_migration_docker_dir }}/backup/{{ jenkins_migration_constants.jenkins_config_file }}.backup"
    remote_src: true
    mode: "0644"
  when: jenkins_migration_discovered_home is defined
  register: config_backup_result
  failed_when: false

- name: Backup - Warn if config backup failed
  ansible.builtin.debug:
    msg: "⚠️  WARNING: Could not backup Jenkins config.xml - {{ config_backup_result.msg | default('Unknown error') }}"
  when:
    - config_backup_result is defined
    - config_backup_result is failed

- name: Backup - Create migration state file
  ansible.builtin.copy:
    content: |
      # Migration backup created: {{ ansible_date_time.iso8601 }}
      ORIGINAL_JENKINS_HOME={{ jenkins_migration_discovered_home }}
      ORIGINAL_JENKINS_PORT={{ jenkins_migration_discovered_port }}
      ORIGINAL_JENKINS_UID={{ jenkins_migration_discovered_uid }}
      ORIGINAL_JENKINS_GID={{ jenkins_migration_discovered_gid }}
      MIGRATION_TYPE=systemd-to-docker
      BACKUP_DATE={{ ansible_date_time.epoch }}
    dest: "{{ jenkins_migration_docker_dir }}/backup/migration-state.env"
    mode: "0644"
