---
# Ansible Collection Requirements for Jenkins Migration Playbook
# Docker Compose v2 Support and Enhanced Validation
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  # Community Docker Collection - Docker Compose v2 Support
  - name: community.docker
    version: ">=3.4.0"
    source: https://galaxy.ansible.com

  # Community General Collection - Enhanced utilities
  - name: community.general
    version: ">=7.0.0"
    source: https://galaxy.ansible.com

  # Ansible POSIX Collection - System modules
  - name: ansible.posix
    version: ">=1.5.0"
    source: https://galaxy.ansible.com
